version: "3.7"
services:
  app:
    build:
      #Quite los argumentos para que pasara el GitHub Action
      #args:
        #user: islasgeci
        #uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: islasgeci
    container_name: islasgeci-app
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/
      - ./var/www/html/vendor
    # networks:
    #   - islasgeci

#   nginx:
#     image: nginx:alpine
#     container_name: islasgeci-nginx
#     restart: unless-stopped
#     ports:
#       - "8000:80"
#     volumes:
#       - ./:/var/www/
#       - ./nginx/conf.d/:/etc/nginx/conf.d/
#     networks:
#       - islasgeci

# networks:
#   islasgeci:
#     driver: bridge
